# Some useful NumPy Array Operations  

NumPy is a Python library that supports support and swift operations for arrays of any dimension. Here are some interesting functionalities that can be implemented using this awesome collection of mathematical functions.

- logspace() for logarithmic scales
- tile() for repetition of array elements
- trigonometric functions
- roots of a polynomial
- solving a system of linear equations

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [4]:
import numpy as np

In [76]:
# List of functions explained 
function1 = np.logspace
function2 = np.tile
function3 = np.sin
function4 = np.polynomial.Polynomial.roots
function5 = np.linalg.solve

## Function 1 - logspace()
Returns an array of numbers evenly spaced out on a logarithmic scale. Default base = 10, size = 50

In [6]:
# Example 1
np.logspace(1, 10)

array([1.00000000e+01, 1.52641797e+01, 2.32995181e+01, 3.55648031e+01,
       5.42867544e+01, 8.28642773e+01, 1.26485522e+02, 1.93069773e+02,
       2.94705170e+02, 4.49843267e+02, 6.86648845e+02, 1.04811313e+03,
       1.59985872e+03, 2.44205309e+03, 3.72759372e+03, 5.68986603e+03,
       8.68511374e+03, 1.32571137e+04, 2.02358965e+04, 3.08884360e+04,
       4.71486636e+04, 7.19685673e+04, 1.09854114e+05, 1.67683294e+05,
       2.55954792e+05, 3.90693994e+05, 5.96362332e+05, 9.10298178e+05,
       1.38949549e+06, 2.12095089e+06, 3.23745754e+06, 4.94171336e+06,
       7.54312006e+06, 1.15139540e+07, 1.75751062e+07, 2.68269580e+07,
       4.09491506e+07, 6.25055193e+07, 9.54095476e+07, 1.45634848e+08,
       2.22299648e+08, 3.39322177e+08, 5.17947468e+08, 7.90604321e+08,
       1.20679264e+09, 1.84206997e+09, 2.81176870e+09, 4.29193426e+09,
       6.55128557e+09, 1.00000000e+10])

The 50 returned numbers are equally spaced on a log scale with base 10, ranging from base^1 to base^10.

In [7]:
# Example 2 - other parameters
np.logspace(1, 10, num=10, base=2)

array([   2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,  512.,
       1024.])

num - count of numbers returned = 10 here  
base - base for the logarithmic scale = 2 here

In [8]:
# Example 3 - breaking
np.logspace(1)

TypeError: _logspace_dispatcher() missing 1 required positional argument: 'stop'

Start and stop are mandatory parameters, while the others are optional.

In [9]:
np.logspace(1, 1000)

/opt/conda/lib/python3.8/site-packages/numpy/core/function_base.py:265: RuntimeWarning: overflow encountered in power
  return _nx.power(base, y)


array([1.00000000e+001, 2.44205309e+021, 5.96362332e+041, 1.45634848e+062,
       3.55648031e+082, 8.68511374e+102, 2.12095089e+123, 5.17947468e+143,
       1.26485522e+164, 3.08884360e+184, 7.54312006e+204, 1.84206997e+225,
       4.49843267e+245, 1.09854114e+266, 2.68269580e+286, 6.55128557e+306,
                   inf,             inf,             inf,             inf,
                   inf,             inf,             inf,             inf,
                   inf,             inf,             inf,             inf,
                   inf,             inf,             inf,             inf,
                   inf,             inf,             inf,             inf,
                   inf,             inf,             inf,             inf,
                   inf,             inf,             inf,             inf,
                   inf,             inf,             inf,             inf,
                   inf,             inf])

Keep a check on the range of numbers asked for - the returned array may contain the infinity value when the valid range is exceeded.  

Use this function in combination with matplotlib to create logarithmic graphs.

## Function 2 - tile()

This function creates arrays by repeating elements (like tiles on a wall) from the array passed as a parameter. 

In [25]:
# Example 1 - 1D array
arr = np.array([2, 5, 7, 8])

number_of_repetitions = 3

tiled_arr = np.tile(arr, number_of_repetitions)
tiled_arr

array([2, 5, 7, 8, 2, 5, 7, 8, 2, 5, 7, 8])

A new array is returned, that contains the elements of the passed array repeated a number of times, also a parameter.

In [26]:
# Example 2 - multidimensional arrays
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6]])

num_repetitions_axis1 = 2
num_repetitions_axis2 = 3

tiled_arr2 = np.tile(arr2, (num_repetitions_axis1,
                            num_repetitions_axis2))
tiled_arr2

array([[1, 2, 3, 1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6, 4, 5, 6],
       [1, 2, 3, 1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6, 4, 5, 6]])

If you want repetitions along different axes, you must pass these values as a tuple in the order of the axis number.  
Note that the array passed as a parameter is automatically promoted to a higher dimension if needed for repetition.

In [31]:
# Example 3 - promotion to higher dimension
arr3 = arr
tiled_arr3 = np.tile(arr3, (2, 2))
tiled_arr3

array([[2, 5, 7, 8, 2, 5, 7, 8],
       [2, 5, 7, 8, 2, 5, 7, 8]])

In any case, the original array is not affected.

In [32]:
arr3

array([2, 5, 7, 8])

In [39]:
# Example 4 - breaking
tiled_arr4 = np.tile(arr3, 3.)

TypeError: 'float' object cannot be interpreted as an integer

Keep in mind that the number of repetitions must be an integer!

This function comes in handy when you want to clone elements of an array in different axes.  
A similar function is [numpy.repeat](https://numpy.org/doc/stable/reference/generated/numpy.repeat.html)

## Function 3 - sin()

Returns the sine value for a given angle (in radians).

In [44]:
# Example 1 
np.sin(30. * np.pi / 180.)

0.49999999999999994

Sine value for 30 degrees or (30 * pi/180) radians is returned (ignore the inaccuracy caused due to the nature of the float datatype).

In [52]:
# Example 2
np.sin(np.array([45., 60., 90.]) * np.pi / 180.)

array([0.70710678, 0.8660254 , 1.        ])

In [53]:
np.sin([45, 90])

array([0.85090352, 0.89399666])

The operation can thus be done on multiple values passed as a NumPy array or a Python list.

Other trigonometric functions (which you can find [here](https://numpy.org/doc/stable/reference/routines.math.html)) work in a similar way. 

You can use these functions whenever trigonometry is required for some functionality.  

## Function 4 - roots()

Returns the roots of a given polynomial.

First, we need to create a polynomial to work with. This can be done using the convenience classes of the numpy.polynomial package.

In [64]:
from numpy.polynomial import Polynomial as poly

In [65]:
# Example 1
p = poly([-12, -4, 1])
p

Polynomial([-12.,  -4.,   1.], domain=[-1,  1], window=[-1,  1])

In [63]:
p.roots()

array([-2.,  6.])

The [roots](https://www.mathsisfun.com/algebra/polynomials-sums-products-roots.html) of the given polynomial are returned.

This works for any n-degree polynomial.

In [67]:
# Example 2 - working
p2 = poly([-6, 11, -6, 1])
p2

Polynomial([-6., 11., -6.,  1.], domain=[-1,  1], window=[-1,  1])

In [68]:
p2.roots()

array([1., 2., 3.])

Remember that you need to have a polynomial to use this function, a normal NumPy array cannot do the job.

In [70]:
# Example 3 - breaking
arr = np.array([-12, -4, 1])
arr.roots()

AttributeError: 'numpy.ndarray' object has no attribute 'roots'

You can find other powerful functionalities and different Convenience classes [here](https://numpy.org/doc/stable/reference/routines.polynomials.classes.html).

## Function 5 - linalg.solve()

This functions takes to matrices and solves them as a system of linear equations that can be represented as AX = B.  
Let's try to solve the system of the following equations:    
$ 3x_0 + 4x_1 = 10 $  
$x_0 - x_1 = 1$

In [78]:
# Example 1 - working
a = np.array([[3, 4], [1, -1]])
b = np.array([10, 1])
x = np.linalg.solve(a, b)
x

array([2., 1.])

$x_0 = 2$ and $x_1 = 1$ satisfy the given set of linear equations. This can be checked by comparing LHS with the RHS as follows.

In [79]:
np.allclose(np.dot(a, x), b)

True

In [95]:
# Example 2 - higher dimension
a2 = np.array([[1, 2, 3], [2, -1, 1], [3, 4, 5]])
b2 = np.array([24, 3, -6])
x2 = np.linalg.solve(a2, b2)
x2

array([-24., -21.,  30.])

In [96]:
np.allclose(np.dot(a2, x2), b2)

True

Unfortunately, this function cannot handle special cases, like no solution, infinitely many solutions.

In [97]:
# Example 3 - This system has no solutions
a3 = np.array([[4, 1], [4, 1]])
b3 = np.array([9, 3])
np.linalg.solve(a3, b3)

LinAlgError: Singular matrix

In [100]:
# Example 4 - this system has infinitely many solutions
a4 = np.array([[0, 0], [1, 1]])
b4 = np.array([0, 1])
np.linalg.solve(a4, b4)

LinAlgError: Singular matrix

Use this function to calculate solutions to linear equations with the swiftness provided by NumPy. However, be sure to keep an eye out for these errors when systems with special solutions are passed.

## Conclusion

We learnt about some NumPy functions, how to use them, when they break, and what we can do with them. Check out the following links to learn more about this incredibly useful library!

## Reference Links

* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* Geeks for Geeks - NumPy : https://www.geeksforgeeks.org/python-numpy
* W3Schools NumPy : https://www.w3schools.com/python/numpy_intro.asp
* Source code for the library : https://github.com/numpy/numpy
